import { type NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import Login from "./Login";
import LandingPage from "./inicio";
import AOSWrapper from "./../utils/AOS";

const Home: NextPage = () => {
	const [isLogged, setIsLogged] = useState<boolean>(false);

	return (
		<>
			<Head>
				<title>Exaya</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/icon.png" />
			</Head>
			<AOSWrapper>
				{isLogged ? <LandingPage /> : <Login setIsLogged={setIsLogged} />}
			</AOSWrapper>
		</>
	);
};

export default Home;
