import { type NextPage } from "next";
import Head from "next/head";

import { useState } from "react";
import Login from "./pages/Login";
import LandingPage from "./pages/LandingPage";

const Home: NextPage = () => {
	const [isLogged, setIsLogged] = useState(false);

	return (
		<>
			<Head>
				<title>Exaya</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				{isLogged ? <LandingPage /> : <Login setIsLogged={setIsLogged} />}
			</main>
		</>
	);
};

export default Home;
