/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoletosIndexRouteImport } from './routes/boletos/index'
import { Route as EncomiendasRastreoRouteImport } from './routes/encomiendas/rastreo'
import { Route as ApiTrpcRouteImport } from './routes/api/trpc'
import { Route as AppSoporteRouteImport } from './routes/_app/soporte'
import { Route as AppPasajesRouteImport } from './routes/_app/pasajes'
import { Route as AppEncomiendasRouteImport } from './routes/_app/encomiendas'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContableRouteImport } from './routes/_app/contable'
import { Route as AppAdministracionRouteImport } from './routes/_app/administracion'
import { Route as BoletosViajeViajeIdRouteImport } from './routes/boletos/viaje/$viajeId'
import { Route as AppViajeViajeIdRouteImport } from './routes/_app/viaje/$viajeId'
import { Route as AppProgramacionViajesRouteImport } from './routes/_app/programacion/viajes'
import { Route as AppProgramacionComprobantesRouteImport } from './routes/_app/programacion/comprobantes'
import { Route as AppProgramacionBusConductorRouteImport } from './routes/_app/programacion/bus-conductor'

const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletosIndexRoute = BoletosIndexRouteImport.update({
  id: '/boletos/',
  path: '/boletos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomiendasRastreoRoute = EncomiendasRastreoRouteImport.update({
  id: '/encomiendas/rastreo',
  path: '/encomiendas/rastreo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcRoute = ApiTrpcRouteImport.update({
  id: '/api/trpc',
  path: '/api/trpc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSoporteRoute = AppSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AppRoute,
} as any)
const AppPasajesRoute = AppPasajesRouteImport.update({
  id: '/pasajes',
  path: '/pasajes',
  getParentRoute: () => AppRoute,
} as any)
const AppEncomiendasRoute = AppEncomiendasRouteImport.update({
  id: '/encomiendas',
  path: '/encomiendas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContableRoute = AppContableRouteImport.update({
  id: '/contable',
  path: '/contable',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministracionRoute = AppAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => AppRoute,
} as any)
const BoletosViajeViajeIdRoute = BoletosViajeViajeIdRouteImport.update({
  id: '/boletos/viaje/$viajeId',
  path: '/boletos/viaje/$viajeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViajeViajeIdRoute = AppViajeViajeIdRouteImport.update({
  id: '/viaje/$viajeId',
  path: '/viaje/$viajeId',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacionViajesRoute = AppProgramacionViajesRouteImport.update({
  id: '/programacion/viajes',
  path: '/programacion/viajes',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacionComprobantesRoute =
  AppProgramacionComprobantesRouteImport.update({
    id: '/programacion/comprobantes',
    path: '/programacion/comprobantes',
    getParentRoute: () => AppRoute,
  } as any)
const AppProgramacionBusConductorRoute =
  AppProgramacionBusConductorRouteImport.update({
    id: '/programacion/bus-conductor',
    path: '/programacion/bus-conductor',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/planes': typeof PlanesRoute
  '/administracion': typeof AppAdministracionRoute
  '/contable': typeof AppContableRoute
  '/dashboard': typeof AppDashboardRoute
  '/encomiendas': typeof AppEncomiendasRoute
  '/pasajes': typeof AppPasajesRoute
  '/soporte': typeof AppSoporteRoute
  '/api/trpc': typeof ApiTrpcRoute
  '/encomiendas/rastreo': typeof EncomiendasRastreoRoute
  '/boletos/': typeof BoletosIndexRoute
  '/programacion/bus-conductor': typeof AppProgramacionBusConductorRoute
  '/programacion/comprobantes': typeof AppProgramacionComprobantesRoute
  '/programacion/viajes': typeof AppProgramacionViajesRoute
  '/viaje/$viajeId': typeof AppViajeViajeIdRoute
  '/boletos/viaje/$viajeId': typeof BoletosViajeViajeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/planes': typeof PlanesRoute
  '/administracion': typeof AppAdministracionRoute
  '/contable': typeof AppContableRoute
  '/dashboard': typeof AppDashboardRoute
  '/encomiendas': typeof AppEncomiendasRoute
  '/pasajes': typeof AppPasajesRoute
  '/soporte': typeof AppSoporteRoute
  '/api/trpc': typeof ApiTrpcRoute
  '/encomiendas/rastreo': typeof EncomiendasRastreoRoute
  '/boletos': typeof BoletosIndexRoute
  '/programacion/bus-conductor': typeof AppProgramacionBusConductorRoute
  '/programacion/comprobantes': typeof AppProgramacionComprobantesRoute
  '/programacion/viajes': typeof AppProgramacionViajesRoute
  '/viaje/$viajeId': typeof AppViajeViajeIdRoute
  '/boletos/viaje/$viajeId': typeof BoletosViajeViajeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/planes': typeof PlanesRoute
  '/_app/administracion': typeof AppAdministracionRoute
  '/_app/contable': typeof AppContableRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/encomiendas': typeof AppEncomiendasRoute
  '/_app/pasajes': typeof AppPasajesRoute
  '/_app/soporte': typeof AppSoporteRoute
  '/api/trpc': typeof ApiTrpcRoute
  '/encomiendas/rastreo': typeof EncomiendasRastreoRoute
  '/boletos/': typeof BoletosIndexRoute
  '/_app/programacion/bus-conductor': typeof AppProgramacionBusConductorRoute
  '/_app/programacion/comprobantes': typeof AppProgramacionComprobantesRoute
  '/_app/programacion/viajes': typeof AppProgramacionViajesRoute
  '/_app/viaje/$viajeId': typeof AppViajeViajeIdRoute
  '/boletos/viaje/$viajeId': typeof BoletosViajeViajeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/features'
    | '/login'
    | '/planes'
    | '/administracion'
    | '/contable'
    | '/dashboard'
    | '/encomiendas'
    | '/pasajes'
    | '/soporte'
    | '/api/trpc'
    | '/encomiendas/rastreo'
    | '/boletos/'
    | '/programacion/bus-conductor'
    | '/programacion/comprobantes'
    | '/programacion/viajes'
    | '/viaje/$viajeId'
    | '/boletos/viaje/$viajeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/features'
    | '/login'
    | '/planes'
    | '/administracion'
    | '/contable'
    | '/dashboard'
    | '/encomiendas'
    | '/pasajes'
    | '/soporte'
    | '/api/trpc'
    | '/encomiendas/rastreo'
    | '/boletos'
    | '/programacion/bus-conductor'
    | '/programacion/comprobantes'
    | '/programacion/viajes'
    | '/viaje/$viajeId'
    | '/boletos/viaje/$viajeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/contacto'
    | '/features'
    | '/login'
    | '/planes'
    | '/_app/administracion'
    | '/_app/contable'
    | '/_app/dashboard'
    | '/_app/encomiendas'
    | '/_app/pasajes'
    | '/_app/soporte'
    | '/api/trpc'
    | '/encomiendas/rastreo'
    | '/boletos/'
    | '/_app/programacion/bus-conductor'
    | '/_app/programacion/comprobantes'
    | '/_app/programacion/viajes'
    | '/_app/viaje/$viajeId'
    | '/boletos/viaje/$viajeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PlanesRoute: typeof PlanesRoute
  ApiTrpcRoute: typeof ApiTrpcRoute
  EncomiendasRastreoRoute: typeof EncomiendasRastreoRoute
  BoletosIndexRoute: typeof BoletosIndexRoute
  BoletosViajeViajeIdRoute: typeof BoletosViajeViajeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boletos/': {
      id: '/boletos/'
      path: '/boletos'
      fullPath: '/boletos/'
      preLoaderRoute: typeof BoletosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomiendas/rastreo': {
      id: '/encomiendas/rastreo'
      path: '/encomiendas/rastreo'
      fullPath: '/encomiendas/rastreo'
      preLoaderRoute: typeof EncomiendasRastreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc': {
      id: '/api/trpc'
      path: '/api/trpc'
      fullPath: '/api/trpc'
      preLoaderRoute: typeof ApiTrpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/soporte': {
      id: '/_app/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AppSoporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pasajes': {
      id: '/_app/pasajes'
      path: '/pasajes'
      fullPath: '/pasajes'
      preLoaderRoute: typeof AppPasajesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/encomiendas': {
      id: '/_app/encomiendas'
      path: '/encomiendas'
      fullPath: '/encomiendas'
      preLoaderRoute: typeof AppEncomiendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contable': {
      id: '/_app/contable'
      path: '/contable'
      fullPath: '/contable'
      preLoaderRoute: typeof AppContableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administracion': {
      id: '/_app/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AppAdministracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/boletos/viaje/$viajeId': {
      id: '/boletos/viaje/$viajeId'
      path: '/boletos/viaje/$viajeId'
      fullPath: '/boletos/viaje/$viajeId'
      preLoaderRoute: typeof BoletosViajeViajeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/viaje/$viajeId': {
      id: '/_app/viaje/$viajeId'
      path: '/viaje/$viajeId'
      fullPath: '/viaje/$viajeId'
      preLoaderRoute: typeof AppViajeViajeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacion/viajes': {
      id: '/_app/programacion/viajes'
      path: '/programacion/viajes'
      fullPath: '/programacion/viajes'
      preLoaderRoute: typeof AppProgramacionViajesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacion/comprobantes': {
      id: '/_app/programacion/comprobantes'
      path: '/programacion/comprobantes'
      fullPath: '/programacion/comprobantes'
      preLoaderRoute: typeof AppProgramacionComprobantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacion/bus-conductor': {
      id: '/_app/programacion/bus-conductor'
      path: '/programacion/bus-conductor'
      fullPath: '/programacion/bus-conductor'
      preLoaderRoute: typeof AppProgramacionBusConductorRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdministracionRoute: typeof AppAdministracionRoute
  AppContableRoute: typeof AppContableRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEncomiendasRoute: typeof AppEncomiendasRoute
  AppPasajesRoute: typeof AppPasajesRoute
  AppSoporteRoute: typeof AppSoporteRoute
  AppProgramacionBusConductorRoute: typeof AppProgramacionBusConductorRoute
  AppProgramacionComprobantesRoute: typeof AppProgramacionComprobantesRoute
  AppProgramacionViajesRoute: typeof AppProgramacionViajesRoute
  AppViajeViajeIdRoute: typeof AppViajeViajeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministracionRoute: AppAdministracionRoute,
  AppContableRoute: AppContableRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEncomiendasRoute: AppEncomiendasRoute,
  AppPasajesRoute: AppPasajesRoute,
  AppSoporteRoute: AppSoporteRoute,
  AppProgramacionBusConductorRoute: AppProgramacionBusConductorRoute,
  AppProgramacionComprobantesRoute: AppProgramacionComprobantesRoute,
  AppProgramacionViajesRoute: AppProgramacionViajesRoute,
  AppViajeViajeIdRoute: AppViajeViajeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactoRoute: ContactoRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PlanesRoute: PlanesRoute,
  ApiTrpcRoute: ApiTrpcRoute,
  EncomiendasRastreoRoute: EncomiendasRastreoRoute,
  BoletosIndexRoute: BoletosIndexRoute,
  BoletosViajeViajeIdRoute: BoletosViajeViajeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
